version: '3.4'

services:
  homework2:
    image: ${DOCKER_REGISTRY-}homework2
    build:
      context: .
      dockerfile: Homework2/Dockerfile
    volumes:
      - data:/app/wwwroot
volumes:
  data: